[package]
name = "rakun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rakun"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.3"
pyo3-asyncio = { version = "0.18.0", features = ["attributes", "tokio-runtime"] }
tokio = "1.29.1"
chrono = "0.4.26"